// next type-checking metadata objects
import type { Metadata } from "next";
// import Inter font utility
import { Inter } from "next/font/google";

// apply Inter font to all text within the body element,
// text content rendered within the body will inherit the Inter font styling
// including any static text content directly within the RootLayout,
// and any child components or elements passed as { children } to RootLayout.
const inter = Inter({ subsets: ["latin"] });

// set app metadata
export const metadata: Metadata = {
  title: "CLi Tool Commands",
  description: "Generated by create next app",
};

// define RootLayout component,
// children prop represents nested components, 
// or elements passed into RootLayout.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
